runtime: python39  # Specifies the Python runtime version
instance_class: F4_1G

handlers:
  - url: /static
    static_dir: static  # Specifies the directory where static files are located

  - url: /templates
    static_dir: templates  # Specifies the directory where template files are located

  - url: .*
    script: auto  # Specifies that all other requests should be handled by Flask
